# Generated by Django 4.0.5 on 2022-06-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manguera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
    ]
