# Generated by Django 4.0.4 on 2022-06-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manguera', '0002_remove_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(default='0', upload_to=''),
            preserve_default=False,
        ),
    ]
