# Generated by Django 4.0.4 on 2022-06-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manguera', '0003_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
