# Generated by Django 4.0.4 on 2022-06-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manguera', '0004_alter_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to='galeria'),
        ),
    ]
