# Generated by Django 4.0.4 on 2022-06-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manguera', '0007_remove_cliente_edad_cliente_correo_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
